site_name: Nelson Day Electrical - WordPress Documentation
nav:
  - General: index.md
  - Header: header.md
  - Footer: footer.md
  - Homepage: home.md
  - Static Page: static.md
  - Blog List: blog-list.md
  - Blog Post: blog-post.md
  - Menu: menu.md
theme: readthedocs
extra_css:
  - style.css
